apiVersion: v1
kind: Service
metadata:
  name: {{ include "dcm.fullname" . }}
  namespace: {{ include "dcm.namespace" . }}
  labels:
    {{- include "dcm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "dcm.selectorLabels" . | nindent 4 }}
  ports:
    - name: app
      port: {{ .Values.service.ports.app.port }}
      targetPort: {{ .Values.service.ports.app.targetPort }}
      protocol: {{ .Values.service.ports.app.protocol }}
    - name: http
      port: {{ .Values.service.ports.http.port }}
      targetPort: {{ .Values.service.ports.http.targetPort }}
      protocol: {{ .Values.service.ports.http.protocol }}
